[GITHUB]
current_commit_sha = "a2adde3ed5da18e4aa5586f438e2bef5d1dca2b1"
current_release_version = "1.0.4"
master_texts_path = "updates\\\\nier-replicant-pt-br-translation-master\\\\texts"
master_url = "https://github.com/Arekushi/nier-replicant-pt-br-translation/archive/master.zip"
last_release_url = "https://api.github.com/repos/Arekushi/nier-replicant-pt-br-translation/releases/latest"
commits_url = "https://api.github.com/repos/Arekushi/nier-replicant-pt-br-translation/commits"

[ARGS]
raw_texts_folder_name = "raw"
source_language = "en"
target_language = "pt"
originals_folder_name = "original"
paths_to_translate = [
    "pt",
]
files_folders_required = [
    "steam_api64.dll",
    "NieR Replicant ver.1.22474487139.exe",
]

[TRANSLATOR]
source = "google"
