[ARGS]
master_url = 'https://github.com/Arekushi/nier-replicant-pt-br-translation/archive/master.zip'
master_texts_path = 'updates\\nier-replicant-pt-br-translation-master\\texts'
raw_texts_folder_name = 'raw'
target_language = 'pt'
source_language = 'en'
originals_folder_name = 'original'
paths_to_translate = [
    'pt'
]

[TRANSLATOR]
source = 'google'

[CHATGPT]
max_characters_phrases = 750
translate_text_request = '''
    Então traduza essas frases, OBEDECENDO o contexto que lhe informei e as REGRAS também.
    (Não se esqueça de sempre manter a sua resposta dentro de um BLOCO DE CÓDIGO em Python)
    (Lembre-se de manter a MESMA QUANTIDADE de frases que eu mandar, se eu te enviei 30, me responda com 30)
    (Strings que estiverem em BRANCO, VAZIAS "" é para deixar assim, NÃO MUDE isso!)
    (Mantenha o índice dentro da sublista, por exemplo [1, 'Uma frase qualquer'], para cada item da lista)
    (Não precisa colocar as frases originais, só responda com as traduções dentro de uma lista em Python, por favor):

    ```python
    [phrases]
    ```
'''
request_text = '''
    Ok, eu vou pedir para que você faça a tradução do Inglês para o Português brasileiro de uma lista de frases.
    As frases vem de um jogo chamado NieR: Replicant, onde temos os protagosnistas: NieR, Kainé e Emil.
    O jogo se passa em um futuro, porém os costumes são medievais.
    Boa parte das frases são de diálogos entre os personagens desse mundo, tenha isso em mente.
    Eu irei te entregar uma lista de sublistas de frases em Python, cada sublista tem tem um índice numérico e
    logo depois uma string (que é a frase que VOCÊ vai traduzir).
    Quero que traduza CADA FRASE o mais fielmente possível,
    mantendo a ESTRUTURA da frase original, se tiver parênteses, reticensias, ponto e vírgula,
    ponto de exclamação e/ou interrogação, NÃO É PRA REMOVER.
    Não remova o índice, matenha ele na estrutura quando me responder.
    Aqui está uma lista de regras a serem seguidas:
    [rules]

    Irei mandar as frases para serem traduzidas gradualmente, e assim você irá ir me respondendo com a tradução, Ok?
'''
rules = [
    '''
        As traduções devem estar dentro de um bloco de código Python
    ''',
    '''
        (Existem partes que estão usando tags, não quero que traduza a tag, o conteúdo dela pode traduzir,
        exemplo se aparecer a tag <LF> não traduza e nem mude sua estrutura).
    ''',
    '''
        Se tiver parênteses na frase, quero que os mantenha na frase, NÃO os remova, faz parte da estrutura da frase.
        Também quero que me retorne no mesmo formato, uma lista de strings no Python.
    ''',
    '''
        Não traduza o nome "Shadowlord", matenha como "Shadowlord"
    ''',
    '''
        Traduza "Shades" para "Sombras"
    ''',
    '''
        Não traduza o nome "Sunshine", matenha como "Sunshine"
    ''',
    '''
        Traduza "Sealed Verse" para "Versos Selados"
    ''',
    '''
        Traduza "Grimoire" para "Grimório"
    ''',
    '''
        Traduza "Facade" para "Facade"
    ''',
    '''
        Traduza "Black Scrawl" para "Rabisco Negro"
    ''',
    '''
        Traduza "Seafront" para "Beira-Mar"
    ''',
    '''
        Traduza "Barren Temple" para "Templo Árido"
    ''',
    '''
        Traduza "Forest of Myth" para "Floresta dos Mitos"
    ''',
    '''
        Termine as frases que tu tentar traduzir, se não conseguir tente novamente
    ''',
    '''
        Não tente traduzir caracteres simulares a estes: "％＠＊※〆＠＊％☆＊"
    ''',
    '''
        Não junte frases, cada frase é individual'
    ''',
    '''
        Se e somente se deixe os pronomes e artigos no masculino se você não sabe o gênero do sujeito
    ''',
    '''
        Se a palavra estiver em caixa alta, mantenha em caixa alta
    ''',
    '''
        Frases em branco como por exemplo ("") é para manter da mesma forma, não apague por favor
    '''
]

[NIER_PATH]
files_folders_required = [
    'data',
    'steam_api64.dll',
    'NieR Replicant ver.1.22474487139.exe'
]

[TYPER]
translator_help = 'Módulo que traduz de forma automática os arquivos de textos de NieR: Replicant.'
translate_ask_help = 'Pergunta de qual maneira deseja traduzir os arquivos.'
chat_gpt_translate_help = 'Realiza a tradução dos arquivos usando o ChatGPT.'
conventional_translate_help = 'Realiza a tradução dos arquivos usando serviços de tradução mais convencionais (Google, Bing etc).'
reimport_help = 'Módulo fundamental para instalação da tradução, recoloca os textos na pasta do jogo.'
reimport_texts_help = 'Uni os textos traduzidos e os originais e os copia para a pasta do jogo.'
manager_help = 'Neste módulo você é capaz de gerenciar a tradução, podendo instalar, desinstalar e atualizar.'
install_help = 'Esse comando executa o processo de instalação da tradução.'
install_delete_data_help = 'Flag para indicar se o usuário deseja ou não apagar a pasta [data] dos arquivos do jogo. É necessário remover a pasta [data] para dar andamento com a tradução, porém podemos apenas mudar o nome da pasta para qualquer outra coisa.'
install_delete_data_prompt = 'Você deseja deletar a pasta [data] do NieR: Replicant? 📂 Se decidir apagar NÃO há como reverter a tradução, você irá precisar baixar o jogo novamente...'
uninstall_help = 'Esse comando executa o processo de desinstalação da tradução.'
update_help = 'Realizará a atualização da tradução, baixando os arquivos do repositório remoto.'
update_redownload_help = 'Caso não queria, também é possível fazer a atualização com os arquivos locais.'
set_nier_path_help = 'Atribui o caminho até os arquivos de NieR: Replicant.'
extractor_help = 'Módulo responsável pela extração de conteúdo do jogo original.'
extract_assets_help = 'Extrai todos os assets (modelos, texturas, textos etc).'
extract_texts_help = 'Lê os arquivos binário que já foram descompactados e transforma em um formato legível - CSV.'

[CLI]
thanks = '''

Obrigado por utilizar! :purple_heart:
Desenvolvido por: https://github.com/Arekushi
Repositório original: https://github.com/Arekushi/nier-replicant-pt-br-translation'''
translator_engine_choice = '🤔 Qual mecanismo de [white on blue] tradução [/] você deseja?'
texts_folder_choice = '💬 Há [b]mais[/] de uma pasta com uma tradução, qual delas você quer?'
translating_rule = ':mechanical_arm: [b]Traduzindo[/]'
extracting_rule = ':pick: [b]Extraindo...[/]'
reimporting_texts_rule = ':rocket: [b]Reimportando os arquivos de texto[/]'
installing_rule = ':new_moon: [b]Instalando a tradução[/]'
installing_status = 'Instalando...'
install_finish = ':white_check_mark: Instalação feita com [white on green] sucesso! [/]'
install_failed = ':x: Instalação [white on red] falhou... [/]'
error_when_copy_content = '''❌ NÃO foi possível copiar os arquivos das pastas [white on blue] movie [/] e [white on blue] sound [/], faça isso manualmente para:

build_path

Também peço que mude o nome da pasta [white on blue] data [/] para qualquer outra coisa, mas não mantenha como está. 😉
'''
extract_assets_except = '''❌ NÃO foi possível extrair os arquivos da sua pasta de NieR.
Peço que verifique ou edite o caminho do seu NieR: Replicant usando o comando:
▶️   manager set-nier-path

E então tente novamente... 😉'''
uninstalling_rule = ':full_moon: [b]Desinstalando a tradução[/]'
uninstalling_status = 'Desinstalando...'
uninstall_finish = ':white_check_mark: Desinstalação feita com [white on green] sucesso! [/]'
uninstall_failed = ':x: Desinstalação [white on red] falhou... [/]'
uninstall_error_delete = ''':warning:  [white on yellow] NÃO [/] foi possível deletar a pasta do caminho:

build_path_var

Peço que se ainda existir uma pasta build_path em seu computador, que a remova manualmente...
'''
updating_rule = ':arrow_up: [b]Fazendo a atualização da tradução...[/]'
updating_status = 'Atualizando...'
update_finish = ':white_check_mark: Atualização feita com [white on green] sucesso! [/]'
update_failed = ':x: Atualização [white on red] falhou... [/]'
update_failed_file_not_found = ''':x: NÃO foi possível atualizar!
:file_folder: Se [b]certifique[/b] que tenha instalado a tradução...

Você pode instalar a tradução usando o comando:
[white on blue] manager install [/]
'''
write_path = ':file_folder: Escreva um [b green]caminho[/] para o [i]NieR: Replicant[/], por favor: '
nier_path_error = ''':x: [b red]Não é um caminho válido![/]
:scroll: É [b yellow]necessário[/] que a [white on blue b] pasta [/] tenha os seguintes itens:'''
download_status = '💻 Fazendo o [white on blue] download [/] do repositório atualizado...'
download_finished = '👍 Download realizado com [white on green] sucesso! [/]'
set_nier_path_finish = ':white_check_mark: Caminho para o [i]NieR: Replicant[/] atribuído com [white on green] sucesso! [/]'
