[TYPER]
translator_help = 'Módulo que traduz de forma automática os arquivos de textos de NieR: Replicant.'
translate_ask_help = 'Pergunta de qual maneira deseja traduzir os arquivos.'
chat_gpt_translate_help = 'Realiza a tradução dos arquivos usando o ChatGPT.'
conventional_translate_help = 'Realiza a tradução dos arquivos usando serviços de tradução mais convencionais (Google, Bing etc).'
reimport_help = 'Módulo fundamental para instalação da tradução, recoloca os textos na pasta do jogo.'
reimport_texts_help = 'Uni os textos traduzidos e os originais e os copia para a pasta do jogo.'
manager_help = 'Módulo com capacidades de gerenciar a tradução, podendo instalar, desinstalar e atualizar.'
install_help = 'Comando que executa o processo de instalação da tradução.'
install_delete_data_help = 'Flag para indicar se o usuário deseja ou não apagar a pasta [data] dos arquivos do jogo. É necessário remover a pasta [data] para dar andamento com a tradução, porém podemos apenas mudar o nome da pasta para qualquer outra coisa.'
install_delete_data_prompt = 'Você deseja deletar a pasta [data] do NieR: Replicant? 📂 Se decidir apagar NÃO há como reverter a tradução, você irá precisar baixar o jogo novamente...'
install_update_texts_help = 'Indica se você deseja fazer o download das atualizações mais recentes do repositório remoto.'
uninstall_help = 'Comando que executa o processo de desinstalação da tradução.'
update_help = 'Comando que realizará a atualização da tradução, baixando os arquivos do repositório remoto.'
update_redownload_help = 'Caso não queria, também é possível fazer a atualização com os arquivos locais.'
set_nier_path_help = 'Atribui o caminho até os arquivos de NieR: Replicant.'
extractor_help = 'Módulo responsável pela extração de conteúdo do jogo original.'
extract_assets_help = 'Extrai todos os assets (modelos, texturas, textos etc).'
extract_texts_help = 'Lê os arquivos binário que já foram descompactados e transforma em um formato legível - CSV.'
