[CLI]
thanks = '''

Obrigado por utilizar! :purple_heart:
Desenvolvido por: https://github.com/Arekushi
Repositório original: https://github.com/Arekushi/nier-replicant-pt-br-translation
'''


[CLI.EXTRACT_ASSETS]
rule = ':wrench: [b]Extraindo assets[/]'
status = 'Extraindo...'


[CLI.EXTRACT_TEXTS]
rule = ':books: [b]Extraindo textos[/]'
status = 'Extraindo...'


[CLI.MAKE_TRANSLATION_FOLDER]
rule= ':hammer_and_wrench: [b]Criação da pasta de tradução[/]'
status = 'Criando...'


[CLI.TRANSLATOR]
rule = ':mechanical_arm: [b]Traduzindo[/]'
repeted = '[bold white on red]Repetindo o envio das frases novamente... (<i>)[/]'
wrong_response = '[bold white on red]Error. Ou a quantidade de frases é diferente ou a mensagem não está no padrão...[/]'
null_return = '[b]Retornando nulo...[/]'
merge_error = '[bold white on red]Infelizmente houve um problema ao realizar o merge, então irei salvar como backup...[/]'
translating_file = '[bold white on blue]Traduzindo... <file>. (<i>/<count_all>)[/]'
file_failed = 'Não foi possível adicionar na lista para traduzir: <file>'


[CLI.NIERPATH]
not_found = ''':stop_sign: A pasta onde o [i]NieR Replicant[/] está instalado [white on red] não [/] foi encontrada ou definida!
:mag_right: [b]EXEMPLO[/] de caminho: [#d1d8e6 on #79a4f4] C:\SteamLibrary\steamapps\common\NieR Replicant ver.1.22474487139 [/]
'''
write_path = ':file_folder: Escreva o [b green]caminho[/] para o [i]NieR: Replicant[/], por favor: '
path_error = ''':x: [b red]Não é um caminho válido![/]
:scroll: É [b yellow]necessário[/] que a [white on blue b] pasta [/] tenha os seguintes itens:'''
finish = ':white_check_mark: Caminho para o [i]NieR: Replicant[/] atribuído com [white on green] sucesso! [/]'


[CLI.INSTALL]
rule = ':new_moon: [b]Instalando a tradução[/]'
status = 'Instalando...'
finish = ':white_check_mark: Instalação feita com [white on green] sucesso! [/]'
failed = ':x: Instalação [white on red] falhou... [/]'
update_version = ':rocket: Identificamos [white on green] atualizações [/] nos textos da tradução, iremos [b]fazer[/] a atualização automaticamente... '
specialk = ':airplane: Será realizada a instalação do [white on green] SpecialK [/] localmente no diretório do NieR: Replicant.'
backup = ':arrow_backward: Será realizado [white on green] o backup [/] dos arquivos que serão modificados.'
backup_file_failed = ':x: [white on red] NÃO [/] foi possível realizar o backup de um dos arquivos!'


[CLI.UNINSTALL]
rule = ':full_moon: [b]Desinstalando a tradução[/]'
status = 'Desinstalando...'
finish = ':white_check_mark: Desinstalação feita com [white on green] sucesso! [/]'
failed = ':x: Desinstalação [white on red] falhou... [/]'
error_delete = ''':warning:  [white on yellow] NÃO [/] foi possível deletar a pasta do caminho:

build_path_var

Peço que se ainda existir uma pasta build_path em seu computador, que a remova manualmente...
'''
error_rename = ''':warning: [white on yellow] NÃO [/] foi possível renomear a pasta [#79a4f4]<name>[/] para seu nome padrão: [#79a4f4]data[/].
:video_game: Recomendo fazer isso manualmente para que o jogo volte a funcionar corretamente.
'''


[CLI.UPDATE]
rule = ':arrow_up: [b]Fazendo a atualização da tradução...[/]'
status = 'Atualizando...'
finish = ':white_check_mark: Atualização feita com [white on green] sucesso! [/]'
failed = ':x: Atualização [white on red] falhou... [/]'
failed_file_not_found = ''':x: NÃO foi possível atualizar!
:file_folder: Se [b]certifique[/b] que tenha instalado a tradução...

Você pode instalar a tradução usando o comando:
[white on blue] manager install [/]
'''
download_finished = '👍 Download realizado com [white on green] sucesso! [/]'
outdated_version_warning = ''':construction: Há uma [green]nova[/] versão dessa aplicação publicada, essa versão está desatualizada!
:wave: Qualquer problema com essa [i]versão[/] peço que [#79a4f4]baixe[/] novamente no link:

https://github.com/Arekushi/nier-replicant-pt-br-translation/releases/download/<version>/nier-translator.zip
'''


[CLI.GENERATE]
rule = ':rocket: [b]Geração dos arquivos .arc[/]'
status = 'Gerando os arquivos...'
finish = ''':white_check_mark: Geração dos arquivos feita com [white on green] sucesso! [/]

Você pode aplicar a tradução localmente usando o comando:
[white on blue] manager install [/]
'''
failed = ':x: A geração de arquivos [white on red] falhou... [/]'
