[GITHUB]
current_commit_sha = "d0f6cfeba59992b7fb49e70e2894988f9fee0134"
current_release_version = "2.0.0"
master_url = "https://github.com/Arekushi/nier-replicant-pt-br-translation/archive/master.zip"
last_release_url = "https://api.github.com/repos/Arekushi/nier-replicant-pt-br-translation/releases/latest"
commits_url = "https://api.github.com/repos/Arekushi/nier-replicant-pt-br-translation/commits"
data_files_urls = [
    "https://raw.githubusercontent.com/Arekushi/nier-replicant-pt-br-translation/master/patch/data/common.arc",
    "https://raw.githubusercontent.com/Arekushi/nier-replicant-pt-br-translation/master/patch/data/info.arc",
]
