[GITHUB]
current_commit_sha = "20081ed06136036718f95c6107c19a52980facf2"
current_release_version = "2.1.0"
master_url = "https://github.com/Arekushi/nier-replicant-pt-br-translation/archive/master.zip"
last_release_url = "https://api.github.com/repos/Arekushi/nier-replicant-pt-br-translation/releases/latest"
commits_url = "https://api.github.com/repos/Arekushi/nier-replicant-pt-br-translation/commits"
files_to_update_urls = [
    [
        "https://raw.githubusercontent.com/Arekushi/nier-replicant-pt-br-translation/master/patch/data.zip",
        "patch",
    ],
    [
        "https://raw.githubusercontent.com/Arekushi/nier-replicant-pt-br-translation/master/patch/textures.zip",
        "patch",
    ],
]
