[GITHUB]
current_release_version = '2.0.0'
current_commit_sha = '6402e23835c78c4f0aa580f12da76f6652456afc'
master_url = "https://github.com/Arekushi/nier-replicant-pt-br-translation/archive/master.zip"
last_release_url = "https://api.github.com/repos/Arekushi/nier-replicant-pt-br-translation/releases/latest"
commits_url = "https://api.github.com/repos/Arekushi/nier-replicant-pt-br-translation/commits"
data_files_urls = [
    'https://raw.githubusercontent.com/Arekushi/nier-replicant-pt-br-translation/master/patch/data/common.arc',
    'https://raw.githubusercontent.com/Arekushi/nier-replicant-pt-br-translation/master/patch/data/info.arc'
]


[ARGS]
target_language = 'pt'
source_language = 'en'
secondary_language = 'es'
paths_to_translate = [
    'translation'
]


[FOLDERS]
raw_texts_folder_name = 'raw'
translation_folder_name = 'translation'
backup_arc_folder_name = 'backup'


[FILES]
required_checkout = [
    'steam_api64.dll',
    'NieR Replicant ver.1.22474487139.exe'
]
text_without_pattern = [
    'text_common\nier_text.txd.csv',
    'talk_all\talker_name.tnd.csv'
]
backup_arc = [
    'common.arc',
    'info.arc'
]


[TOOLS]
ntt_zip = 'tools\\text-tool.zip'
emil_zip = 'tools\\emil-kaine.zip'
arc_zip = 'tools\\arc-tool.zip'
arc_path = 'tools\\arc-tool'
emil_exe = 'tools\\emil-kaine\\emil.exe'
ntt_exe = 'tools\\text-tool\\ntt.exe'
reptext_exe = 'tools\\arc-tool\\reptext.exe'
zstd_exe = 'tools\\arc-tool\\zstd\\zstd.exe'
tools_array = [
    'tools\\text-tool.zip',
    'tools\\emil-kaine.zip',
    'tools\\arc-tool.zip'
]


[DEFAULT_PATHS]
tmp = 'tmp'
tmp_error = 'tmp\\error'
tomls = 'config\\toml'
extracted_assets = 'build_assets\\rom\\pc'
extracted_texts = 'snow\\text'
patch_data = 'patch\\data'
patch_source = 'patch\\source'


[COLUMNS]
to_translate = { InfoWindow = [1, 0], default = [0] }
from_raw = { nier_text = [-8], talker_name = [-8], InfoWindow = [-1, -2], default = [-1] }
