[GITHUB]
current_commit_sha = '6402e23835c78c4f0aa580f12da76f6652456afc'
current_release_version = '1.0.5'
master_texts_path = "updates\\nier-replicant-pt-br-translation-master\\texts"
master_data_path = "updates\\nier-replicant-pt-br-translation-master\\data"
master_url = "https://github.com/Arekushi/nier-replicant-pt-br-translation/archive/master.zip"
last_release_url = "https://api.github.com/repos/Arekushi/nier-replicant-pt-br-translation/releases/latest"
commits_url = "https://api.github.com/repos/Arekushi/nier-replicant-pt-br-translation/commits"


[ARGS]
target_language = 'pt'
source_language = 'en'
secondary_language = 'es'
paths_to_translate = [
    'translation'
]

[FOLDERS]
raw_texts_folder_name = 'raw'
originals_folder_name = 'original'
translation_folder_name = 'translation'
result_folder_name = 'result'
files_folders_required = [
    'steam_api64.dll',
    'NieR Replicant ver.1.22474487139.exe'
]
folders_to_copy = [
    'movie',
    'sound'
]
files_without_pattern = [
    'text_common\nier_text.txd.csv',
    'talk_all\talker_name.tnd.csv'
]

[TOOLS]
ntt_zip = "tools\\text-tool.zip"
emil_zip = "tools\\emil-kaine.zip"
arc_zip = "tools\\arc-tool.zip"

emil_exe = 'tools\\emil-kaine\\emil.exe'
ntt_exe = 'tools\\text-tool\\ntt.exe'
reptext_exe = 'tools\\arc-tool\\reptext.exe'
zstd_exe = 'tools\\arc-tool\\zstd\\zstd.exe'


[DEFAULT_PATHS]
tomls_path = 'config\\toml'
extracted_files_path = 'build_assets\\rom\\pc'
extracted_texts_path = 'snow\\text'
