[TYPER.TRANSLATOR]
help = 'Comando que traduz de forma automática os arquivos de textos de NieR: Replicant.'
use_chatgpt_help = 'Esse marcador define o uso do Google Tradutor para a tradução.'
chat_gpt_help = 'Realiza a tradução dos arquivos usando o ChatGPT.'
conventional_help = 'Realiza a tradução dos arquivos usando serviços de tradução mais convencionais (Google, Bing etc).'
use_api_help = 'Esse marcador define o uso da API do OpenAI ao invés do uso de um WebCrawler.'


[TYPER.REIMPORT]
help = 'Módulo fundamental para instalação da tradução, recoloca os textos na pasta do jogo.'
texts_help = 'Uni os textos traduzidos e os originais e os copia para a pasta do jogo.'


[TYPER.INSTALL]
help = 'Comando que realizará o processo de instalação/atualização da tradução.'
specialk_help = 'Esse marcador define que será instalado o Mod SpecialK localmente na pasta do NieR: Replicant, com o objetivo de utilizar as texturas traduzidas.'
do_update_help = 'Esse marcador define que a instalação irá baixar os arquivos mais atualizados do repositório remoto.'
force_update_help = 'Esse marcador define que o update será forçado, ignorando quaisquer verificações padrão.'


[TYPER.UNINSTALL]
help = 'Comando que realizará o processo de desinstalação da tradução.'
specialk_help = 'Esse mercador define que o Mod SpecialK será desinstalado junto com a tradução.'


[TYPER.MANAGER]
help = 'Módulo com capacidades de gerenciar a tradução, podendo instalar, desinstalar e atualizar.'


[TYPER.BUILDER]
help= 'Módulo com capacidades de extrair os arquivos originais do jogo, extrair os textos, e traduzir usando alguma ferramenta de tradução.'


[TYPER.EXTRACT_ASSETS]
help = 'Extrai todos os assets (modelos, texturas, textos etc).'


[TYPER.EXTRACT_TEXTS]
help = 'Lê os arquivos binário que já foram descompactados e transforma em um formato legível - CSV.'


[TYPER.MAKE_TRANSLATION_FOLDER]
help = 'Pega os textos de duas línguas (source e secundária) e agrupa em arquivos .CSV amigáveis para tradução e revisão.'


[TYPER.GENERATE]
help = 'Comando capaz de gerar arquivos .arc da tradução que estão na pasta (data) do Nier Replicant.'
