[TYPER.TRANSLATOR]
help = 'Comando que traduz de forma automática os arquivos de textos de NieR: Replicant.'
use_chatgpt_help = 'Esse marcador define o uso do Google Tradutor para a tradução.'
chat_gpt_help = 'Realiza a tradução dos arquivos usando o ChatGPT.'
conventional_help = 'Realiza a tradução dos arquivos usando serviços de tradução mais convencionais (Google, Bing etc).'
use_api_help = 'Esse marcador define o uso da API do OpenAI ao invés do uso de um WebCrawler.'


[TYPER.REIMPORT]
help = 'Módulo fundamental para instalação da tradução, recoloca os textos na pasta do jogo.'
texts_help = 'Uni os textos traduzidos e os originais e os copia para a pasta do jogo.'


[TYPER.INSTALL]
help = 'Comando que realizará o processo de instalação da tradução.'
delete_data_help = 'Flag para indicar se o usuário deseja ou não apagar a pasta [data] dos arquivos do jogo. É necessário remover a pasta [data] para dar andamento com a tradução, porém podemos apenas mudar o nome da pasta para qualquer outra coisa.'
delete_data_prompt = 'Você deseja deletar a pasta [data] do NieR: Replicant? 📂 Se decidir apagar NÃO há como reverter a tradução, você irá precisar baixar o jogo novamente...'
update_texts_help = 'Indica se você deseja fazer o download das atualizações mais recentes do repositório remoto.'
do_update_help = 'Esse marcador define se será realizado o update do repositório remoto do Github ou não.'


[TYPER.UNINSTALL]
help = 'Comando que realizará o processo de desinstalação da tradução.'


[TYPER.UPDATE]
help = 'Comando que realizará a atualização da tradução, baixando os arquivos do repositório remoto.'
do_download_help = 'Esse marcador define que não será baixado os textos do repositório remoto do Github, ele utiliza o textos locais.'
redownload_help = 'Caso não queria, também é possível fazer a atualização com os arquivos locais.'


[TYPER.MANAGER]
help = 'Módulo com capacidades de gerenciar a tradução, podendo instalar, desinstalar e atualizar.'


[TYPER.BUILDER]
help= 'Módulo com capacidades de extrair os arquivos originais do jogo, extrair os textos, e traduzir usando alguma ferramenta de tradução.'


[TYPER.EXTRACT_ASSETS]
help = 'Extrai todos os assets (modelos, texturas, textos etc).'


[TYPER.EXTRACT_TEXTS]
help = 'Lê os arquivos binário que já foram descompactados e transforma em um formato legível - CSV.'


[TYPER.MAKE_TRANSLATION_FOLDER]
help = 'Pega os textos de duas línguas (source e secundária) e agrupa em arquivos .CSV amigáveis para tradução e revisão.'


[TYPER.GENERATE]
help = 'Comando capaz de gerar arquivos .arc da tradução que estão na pasta (data) do Nier Replicant.'
